# R for Data Science
```{r}
library(tidyverse)
```
## Whole game
### Data visualisation

Import data libraries
```{r}
library(palmerpenguins)
# library(ggthemes) # <- (optional) provides colorblind safe color palettes
penguins
```

Preview of table
```{r}
glimpse(penguins)
View(penguins)
```

Example from the book:
```{r}
ggplot(
    data= penguins, # pass the data to plotter object
    mapping= aes( # aesthetics (axis)
      x= flipper_length_mm, 
      y= body_mass_g,
      # color = species
    ) 
)+ 
  geom_point(aes(color = species))+ # scatter_plot
  geom_smooth(method = "lm")+ # linear regression model
  labs(
    title = "Body mass and flipper length",
    subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
    x = "Flipper length (mm)",
    y = "Body mass (g)",
    # color = "Species",
    shape = "Species"
  )
```

**Exercises**
```{r}
# 1. How many rows are in penguins? How many columns?
print("There are", dim(penguins)[1], "rows and", dim(penguins)[2], "columns.")

# 2. What does the bill_depth_mm variable in the penguins data frame describe? Read the help for ?penguins to find out.

# 3. Make a scatterplot of bill_depth_mm vs. bill_length_mm. That is, make a scatterplot with bill_depth_mm on the y-axis and bill_length_mm on the x-axis. Describe the relationship between these two variables.

# 4. What happens if you make a scatterplot of species vs. bill_depth_mm? What might be a better choice of geom?
```