# R for Data Science: Data visualization
```{r}
library(tidyverse)
```

Import data libraries
```{r}
library(palmerpenguins)
# library(ggthemes) # <- (optional) provides colorblind safe color palettes
penguins
```

Preview of table
```{r}
glimpse(penguins)
View(penguins)
```

#### 1.2 First steps
Example from the book:
```{r}
ggplot(
    data= penguins, # pass the data to plotter object
    mapping= aes( # aesthetics (axis)
      x= flipper_length_mm, 
      y= body_mass_g,
      # color = species
    ) 
)+ 
  geom_point(
    aes(color = species)
    )+ # scatter_plot
  geom_smooth(method = "lm")+ # linear regression model
  labs(
    title = "Body mass and flipper length",
    subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
    x = "Flipper length (mm)",
    y = "Body mass (g)",
    color = "Species",
    shape = "Species"
  )
```

**1.2.5 Exercises**
```{r}
# 1. How many rows are in penguins? How many columns?
print(paste("There are", dim(penguins)[1], "rows and", dim(penguins)[2], "columns."))

# 2. What does the bill_depth_mm variable in the penguins data frame describe? Read the help for ?penguins to find out.
?penguins
print("`bill_depth_mm` variable in penguins data describes the bill depth in millimeters.")

# 3. Make a scatterplot of bill_depth_mm vs. bill_length_mm. That is, make a scatterplot with bill_depth_mm on the y-axis and bill_length_mm on the x-axis. Describe the relationship between these two variables.
ggplot(
  data = penguins,
  mapping = aes(
    x = bill_length_mm,
    y = bill_depth_mm
    # x = bill_depth_mm,
    # y = bill_length_mm
  )
)+
    geom_point(aes(color = species))+ # scatter_plot
    geom_smooth(method = "lm") # linear regression model

print("The different species form clusters, other then that I do not see a strong relation.")
```

```{r}
ggplot(
  data = penguins, 
  aes(x = bill_depth_mm, y = bill_length_mm)
) + 
  geom_point()+ # scatter_plot
  geom_smooth(method = "lm")
```


```{r}
# 4. What happens if you make a scatterplot of species vs. bill_depth_mm? What might be a better choice of geom?
ggplot(
  data = penguins,
  mapping = aes(
    x = species,
    y = bill_depth_mm
  )
)+
    geom_point() # scatter_plot

print("Better choice would be a type of boxplot:")

ggplot(
  data = penguins,
  mapping = aes(
    x = species,
    y = bill_depth_mm
  )
)+
  geom_violin()+ # scatter_plot
  geom_boxplot(width = 0.1)

```

```{r}
# 5. Why does the following give an error and how would you fix it?
# ggplot(data = penguins) + 
#   geom_point()

print("Because no mapping was given that denotes what needs to be on the axes of the graph.")
```

```{r}
# 6. What does the na.rm argument do in geom_point()? 
# What is the default value of the argument? 
# Create a scatterplot where you successfully use this argument set to TRUE.

print("The penguins dataset contains rows where there are missing values. This generates a warning when plotting the data points. `na.rm` (of which the default state is inactive due to the default value FALSE) removes these rows.")

ggplot(
  data = penguins,
  mapping = aes(
    x = bill_length_mm,
    y = bill_depth_mm
    # x = bill_depth_mm,
    # y = bill_length_mm
  )
)+
    geom_point(aes(color = species), na.rm = TRUE) # scatter_plot

```

```{r}
# 7. Add the following caption to the plot you made in the previous exercise: 
# “Data come from the palmerpenguins package.” 
# Hint: Take a look at the documentation for labs().

ggplot(
  data = penguins,
  mapping = aes(
    x = bill_length_mm,
    y = bill_depth_mm
    # x = bill_depth_mm,
    # y = bill_length_mm
  )
)+
  geom_point(aes(color = species), na.rm = TRUE)+ # scatter_plot
  labs(
    caption = "Data come from the palmerpenguins package."
  )

```

```{r}
# Recreate the following visualization. 
# What aesthetic should bill_depth_mm be mapped to? 
# And should it be mapped at the global level or at the geom level?

ggplot(
  data = penguins,
  mapping = aes(
    x = flipper_length_mm,
    y = body_mass_g,
    
  )
)+
  geom_point(aes(color = bill_depth_mm))+
  geom_smooth(method = "loess") # local polynomial regression

```

```{r}
# Run this code in your head and predict what the output will look like. 
# Then, run the code in R and check your predictions.

print("It will plot flipper_length_mm on the `x` and body_mass_g on the `y`. Each point will get the color that represents its island location. `se` displays the confidence interval, thus only a line will be visible.")

ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, 
                y = body_mass_g, 
                color = island)
) +
  geom_point() +
  geom_smooth(se = FALSE)

print("I forgot that it would be multiple lines..")


```

```{r}
# 10. Will these two graphs look different? Why/why not?

print("I think the same")

ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point() +
  geom_smooth()

ggplot() +
  geom_point(
    data = penguins,
    mapping = aes(x = flipper_length_mm, y = body_mass_g)
  ) +
  geom_smooth(
    data = penguins,
    mapping = aes(x = flipper_length_mm, y = body_mass_g)
  )

```

#### 1.4 Visualizing distributions

**Exercise 1.4.3**
```{r}
# 1. Make a bar plot of species of penguins, where you assign species to the y aesthetic. How is this plot different?
ggplot(
  penguins,
  aes(
    y= fct_infreq(species)
  )
)+
  geom_bar()

print("It's now a horizontal bar chart")
```

```{r}
# 2. How are the following two plots different? 
# Which aesthetic, color or fill, is more useful for changing the color of bars?
ggplot(penguins, aes(x = species)) +
  geom_bar(color = "red")

ggplot(penguins, aes(x = species)) +
  geom_bar(fill = "red")

print('color is the outline of the graph, fill is ..literaly the filling of the figure..')

```

```{r}
# 3. What does the bins argument in geom_histogram() do?
print("`bins` is the size of the 'boxes' were the values will be sorted into.")

```

```{r}
# 4. Make a histogram of the carat variable in the diamonds dataset that is available when you load the tidyverse package. 
# Experiment with different binwidths. 
# What binwidth reveals the most interesting patterns?
glimpse(diamonds)

ggplot(
  diamonds,
  aes(
    x= carat
  )
)+
  # geom_histogram(bins = 6)
  # geom_histogram(binwidth = 1)
  geom_histogram(binwidth = 0.25)


```

#### 1.5 Visualizing relationships

**Exercises 1.5**
```{r}
# 1. The mpg data frame that is bundled with the ggplot2 package contains 234 observations collected by the US Environmental Protection Agency on 38 car models. 
# Which variables in mpg are categorical? 
# Which variables are numerical? (Hint: Type `?mpg` to read the documentation for the dataset.) 
# How can you see this information when you run mpg?

glimpse(mpg)
print('Columns with <chr> contain variables that are categorical.')
print('Columns with <int> or <dbl> contain variables that are numerical.')

```

```{r}
# 2. Make a scatterplot of hwy vs. displ using the mpg data frame. Next, map a third, 
# numerical variable to color, then size, then both color and size, then shape. 
# How do these aesthetics behave differently for categorical vs. numerical variables?

ggplot(
  mpg,
  aes(
    x= displ,
    y= hwy,
    color= cty
  )
)+
  geom_point()

print('`Shape` is more suitable for categorical variables, `size` is more suitable for numerical. Color is suitable for both.')

```

```{r}
# In the scatterplot of hwy vs. displ, what happens if you map a third variable to linewidth?

ggplot(
  mpg,
  aes(
    x= displ,
    y= hwy,
    linewidth= year
    
  )
)+
  geom_point()

print("linewidth is not an attribute of geom_point, thus therefore not plotted.")
```

```{r}
# 5. Make a scatterplot of bill_depth_mm vs. bill_length_mm and color the points by species. 
# What does adding coloring by species reveal about the relationship between these two variables? 
# What about faceting by species?

ggplot(
  penguins,
  aes(
    x= bill_length_mm,
    y= bill_depth_mm,
    color= species
  )
)+
  geom_point()

print("Species are nicely clustered: The bills of Chinstraps tends to have more depth than Gentoos and tends to be longer than Adelies.")
```

```{r}
# 6. Why does the following yield two separate legends? How would you fix it to combine the two legends?

ggplot(
  data = penguins,
  mapping = aes(
    x = bill_length_mm, y = bill_depth_mm, 
    color = species, shape = species
  )
) +
  geom_point() #+
  # labs(color = "Species")

```

```{r}
# 7. Create the two following stacked bar plots. Which question can you answer with the first one? Which question can you answer with the second one?
ggplot(penguins, aes(x = island, fill = species)) +
  geom_bar(position = "fill")
ggplot(penguins, aes(x = species, fill = island)) +
  geom_bar(position = "fill")
```

#### 1.6 Saving your plots

**Exercises 1.6**
```{r}
# 1.Run the following lines of code. Which of the two plots is saved as mpg-plot.png? Why?
print("The scatterplot, because that's the most recent plot.")

ggplot(mpg, aes(x = class)) +
  geom_bar()
ggplot(mpg, aes(x = cty, y = hwy)) +
  geom_point()
# ggsave("mpg-plot.png")
```

```{r}
# What do you need to change in the code above to save the plot as a PDF instead of a PNG? 
# How could you find out what types of image files would work in ggsave()?

print("change suffix.")

ggplot(mpg, aes(x = class)) +
  geom_bar()
ggplot(mpg, aes(x = cty, y = hwy)) +
  geom_point()
# ggsave("mpg-plot.pdf")

```

#### END
```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

